In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("/home/jamesrunnalls/git/thetis/data/Level0/Decimated_Resolution_txt/00314868_ACD_ACS.txt", sep='\t', skiprows=9, header=None, error_bad_lines=False)
cols = ["Timestamp (s)","Depth (dbar)", "Depth Timestamp (s)", "serial #", "on secs", "num wvl", "C ref dark", "C ref counts*num wvl", "C sig dark", "C sig counts*num wvl", "A ref dark", "A ref counts*num wvl", "A sig dark", "A sig counts*num wvl", "ext temp counts", "int temp counts", "pressure counts"]
df.columns = cols + list(range(0, len(df.columns) - len(cols)))
df = df[df['on secs'].notna()]

FileNotFoundError: [Errno 2] No such file or directory: '/home/jamesrunnalls/git/thetis/data/Level0/Decimated_Resolution_txt/00314868_ACD_ACS.txt'

In [69]:
10 - np.nan

nan

In [20]:
df = pd.read_csv("/home/jamesrunnalls/git/thetis/calibration/HPE557A.cal", delim_whitespace=True, skiprows=31, 
                 header=None, error_bad_lines=False, skipfooter=20)
df.columns = []

/home/jamesrunnalls/anaconda3/envs/thetis/lib/python3.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  


In [21]:
df

,0,1,2,3,4,5,6
0,ED,305.210000,'uW/cm^2/nm',2.000,BU,0.0,NONE
1,ED,308.560000,'uW/cm^2/nm',2.000,BU,0.0,NONE
2,ED,311.910000,'uW/cm^2/nm',2.000,BU,0.0,NONE
3,ED,315.270000,'uW/cm^2/nm',2.000,BU,0.0,NONE
4,ED,318.620000,'uW/cm^2/nm',2.000,BU,0.0,NONE
5,ED,321.970000,'uW/cm^2/nm',2.000,BU,0.0,NONE
6,ED,325.330000,'uW/cm^2/nm',2.000,BU,0.0,NONE
7,ED,328.680000,'uW/cm^2/nm',2.000,BU,0.0,NONE
8,ED,332.040000,'uW/cm^2/nm',2.000,BU,0.0,NONE
9,ED,335.390000,'uW/cm^2/nm',2.000,BU,0.0,NONE


In [35]:
file = "/home/jamesrunnalls/git/thetis/calibration/HPE557A.cal"

In [57]:
data = []
with open(file) as f:
    lines = list(f)
    for idx, line in enumerate(lines):
        if "uW/cm^2/nm" in line:
            if "OPTIC3" in line:
                line_arr = line.replace("\n", "").split(" ") + lines[idx + 1].replace("\n", "").split("\t")
            else:
                line_arr = line.replace("\n", "").split(" ") + [np.nan] * 4
            data.append(line_arr)
df = pd.DataFrame(data, columns=["ED", "val", "unit", "no1", "BU", "no2", "type", "a0", "a1", "Im", "Cint"])

In [63]:
a0 = np.array(df["a0"]).astype("float")
a1 = np.array(df["a1"]).astype("float")
Im = np.array(df["Im"]).astype("float")
Cint = np.array(df["Cint"]).astype("float")

In [61]:
a0

array([    nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan, 823.941,
       820.882, 821.191, 820.75 , 823.353, 817.456, 823.118, 819.162,
       820.176, 820.397, 821.382, 823.779, 819.015, 821.324, 820.456,
       818.882, 815.368, 820.529, 821.015, 819.618, 821.368, 821.353,
       817.456, 819.632, 822.897, 823.397, 822.794, 822.515, 823.559,
       823.324, 819.338, 822.412, 822.809, 819.294, 825.853, 824.471,
       821.324, 825.324, 823.   , 822.471, 826.632, 821.897, 819.029,
       822.485, 820.676, 821.529, 822.397, 818.147, 823.074, 820.882,
       818.588, 821.985, 820.176, 823.191, 824.176, 824.088, 820.941,
       824.882, 819.912, 818.794, 821.544, 818.471, 822.088, 823.059,
       819.485, 821.515, 819.044, 821.221, 821.809, 820.618, 821.059,
       817.529, 819.529, 819.588, 821.882, 820.441, 821.074, 821.882,
       821.   , 821.412, 819.662, 821.074, 821.162, 821.912, 819.529,
       822.176, 820.

In [88]:
a = np.array([[2,3,2],[5,6,1]])
b = np.array([3,5])
c = a * b[:, None]

In [89]:
a

array([[2, 3, 2],
       [5, 6, 1]])

In [96]:
a[0, :]

array([2, 3, 2])

In [67]:
c

array([[ 6,  9,  6],
       [25, 30,  5]])

In [68]:
b[:, None]

array([[3],
       [5]])

In [72]:
x = np.full([5,2], np.nan)
x

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [73]:
x[:,0]    

array([nan, nan, nan, nan, nan])

In [74]:
np.nan - 0

nan

In [49]:
file = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/acs286.dev"

In [82]:
import pandas as pd
import numpy as np
import os
from operator import itemgetter


file = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/acs286.dev"


wC_wA_C0_A0 = []
C_corr = []
A_corr = []

with open(file) as f:
    lines = list(f)
    for idx, line in enumerate(lines):
        if "tcal" in line:
            t_cal = line.replace("\n", "").split(" ")
        if "number of temperature bins" in line:
            l_n_t_bins = line.replace("\t", "").split(";")
            n_t_bins = int(l_n_t_bins[0])
        if "temperature bins" in line:
            l_t_bins = line.split("\t")
        if "C and A offset, and C and A temperature correction info" in line:
            char_to_replace = {'C': '',
                               'A': ''}
            for key, value in char_to_replace.items():
                line = line.replace(key, value)
            
            line_arr = line.replace("\n", "").split("\t")
            
            wC_wA_C0_A0.append(itemgetter(0,1,3,4)(line_arr))
            C_corr_temp = list(map(float, np.transpose(line_arr[6:6+n_t_bins-1])))
            A_corr_temp = list(map(float, np.transpose(line_arr[7+n_t_bins:7+2*n_t_bins-1])))
            C_corr.append(C_corr_temp)
            A_corr.append(A_corr_temp)
            
tcal = float(t_cal[1])
ical = float(t_cal[4])
t_bins = list(map(float, l_t_bins[5:5+n_t_bins]))

df = pd.DataFrame(wC_wA_C0_A0, columns=["wC", "wA", "C0", "A0"])

C_corr = np.array(C_corr).astype("float")
A_corr = np.array(A_corr).astype("float")
landa_C = np.array(df["wC"]).astype("float")
C0 = np.array(df["C0"]).astype("float")
landa_A = np.array(df["wA"]).astype("float")
A0 = np.array(df["A0"]).astype("float")

In [83]:
df

,wC,wA,C0,A0
0,400.1,398.5,-1.1268,0.031727
1,403.9,402.6,-0.967835,0.138826
2,407.5,406.2,-0.829249,0.225513
3,411.0,409.6,-0.701859,0.297068
4,414.6,413.2,-0.584462,0.360795
...,...,...,...,...
76,723.7,723.2,-0.373119,0.618488
77,727.6,727.2,-0.627906,0.369199
78,731.8,731.0,-0.887958,0.110622
79,735.3,734.8,-1.118503,-0.122754


In [84]:
def read_acs_calibration_data(file):
    wC_wA_C0_A0 = []
    C_corr = []
    A_corr = []

    with open(file) as f:
        lines = list(f)
        for idx, line in enumerate(lines):
            if "tcal" in line:
                t_cal = line.replace("\n", "").split(" ")
            if "number of temperature bins" in line:
                l_n_t_bins = line.replace("\t", "").split(";")
                n_t_bins = int(l_n_t_bins[0])
            if "temperature bins" in line:
                l_t_bins = line.split("\t")
            if "C and A offset, and C and A temperature correction info" in line:
                char_to_replace = {'C': '',
                               'A': ''}
                for key, value in char_to_replace.items():
                    line = line.replace(key, value)
                line_arr = line.replace("\n", "").split("\t")
                wC_wA_C0_A0.append(itemgetter(0,1,3,4)(line_arr))
                C_corr_temp = list(map(float, np.transpose(line_arr[6:6+n_t_bins-1])))
                A_corr_temp = list(map(float, np.transpose(line_arr[7+n_t_bins:7+2*n_t_bins-1])))
                C_corr.append(C_corr_temp)
                A_corr.append(A_corr_temp)
            
    tcal = float(t_cal[1])
    ical = float(t_cal[4])
    t_bins = list(map(float, l_t_bins[5:5+n_t_bins]))
    
    df = pd.DataFrame(wC_wA_C0_A0, columns=["wC", "wA", "C0", "A0"])
    
    C_corr = np.array(C_corr).astype("float")
    A_corr = np.array(A_corr).astype("float")
    landa_C = np.array(df["wC"]).astype("float")
    C0 = np.array(df["C0"]).astype("float")
    landa_A = np.array(df["wA"]).astype("float")
    A0 = np.array(df["A0"]).astype("float")
    return tcal, ical, t_bins, landa_C, landa_A, C0, A0, C_corr, A_corr

In [85]:
import pandas as pd
import numpy as np
import os
import re
import sys
import glob
import math
import statistics
import matplotlib.pyplot as plt
import datetime as dt
from datetime import datetime, timezone
from copy import deepcopy
import json

calibration_dir = "/Users/camil/Documents/GitRepos/ThetisDatalakes/thetis-vertical-profiler/calibration/"

with open(os.path.join(calibration_dir, "calibration.json"), "r") as f:
    calibration = json.load(f)
    tcal, ical, t_bins, landa_C, landa_A, C0, A0, C_corr, A_corr = read_acs_calibration_data(os.path.join(calibration_dir, "acs380.dev"))

In [87]:
read_acs_calibration_data(os.path.join(calibration_dir, "acs380.dev"))

(22.3,
 19.6,
 [0.916045,
  1.228939,
  2.431034,
  3.4845,
  4.549524,
  5.4832,
  6.507391,
  7.466,
  8.498,
  9.4936,
  10.496667,
  11.497917,
  12.484348,
  13.486667,
  14.496,
  15.51,
  16.4912,
  17.50087,
  18.509565,
  19.498333,
  20.503913,
  21.539643,
  22.448182,
  23.531739,
  24.431333,
  25.5025,
  26.54,
  27.449545,
  28.554167,
  29.438214,
  30.505263,
  31.538438,
  32.4625,
  33.584516,
  34.406538],
 array([400.9, 403.7, 406.6, 410. , 412.8, 416. , 419.4, 423.3, 427.6,
        431.7, 434.8, 438.4, 442.3, 446.3, 450.9, 455. , 458.9, 462.7,
        466.9, 471.5, 476.4, 481. , 485.3, 489.7, 493.5, 497.7, 501.2,
        505.5, 510.4, 515.1, 519.7, 524.2, 528. , 531.7, 535.6, 539.4,
        543.8, 548. , 552.1, 556.2, 560.8, 565. , 569.1, 573.4, 577.1,
        581.2, 585.2, 588.5, 592.7, 596.6, 600.8, 605.3, 609.2, 613.7,
        618. , 622.4, 626.4, 630.9, 634.5, 638.8, 643. , 647.3, 651.6,
        656. , 660.6, 665.2, 669.5, 673.9, 678.3, 682.4, 686.1, 690.2,
  

In [ ]:


tab_corr.to_numpy()